import React from "react";
import { useRouter } from "next/router";
import Headerleft from '../../components/headerleft'
import Headerright from '../../components/headerright'
import Questionpost from '../../components/questionpost'
import Head from "next/head";

const question = () => {
  
  const router = useRouter();
  const { question } = router.query;
  return (
    <>
      <Head>
        <title>{question} | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      
      <div className='flex flex-col space-y-2'>
          {/* nav bar */}
          <div className='flex justify-between lg:space-x-2 '>
            <Headerleft />
            <Headerright />
          </div>
          <div className='flex justify-between lg:space-x-2'>
            <Questionpost />
            <Headerright />
          </div>
      </div>
    </>
  );
  
};

export default question;
